services:
  tun2socks:
    container_name: tun2socks-${INSTANCE_ID}
    image: xjasonlyu/tun2socks
    restart: always
    environment:
      - LOGLEVEL=info
      - PROXY=${PROXY_URL}
      - EXTRA_COMMANDS=ip rule add iif lo ipproto udp dport 53 lookup main;
    cap_add:
      - NET_ADMIN
    networks:
      - my_shared_proxy_network
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 1.0.0.1
      - 8.8.4.4
    init: true                       # Ensures proper process management
    privileged: false                # Try to keep this false if cap_add works
    stop_grace_period: 1m
    sysctls:
      - net.ipv4.ip_forward=1        # Allows the container to route traffic
      - net.ipv6.conf.all.disable_ipv6=0
    security_opt:
      - no-new-privileges:true  
    volumes:
      - /dev/net/tun:/dev/net/tun
    cpus: ${TUN2SOCKS_CPU_LIMIT}
    mem_limit: ${TUN2SOCKS_RAM_LIMIT}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traffmonetizer:
    image: traffmonetizer/cli_v2
    container_name: traffmonetizer-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    command: start accept --token "tbOBkhRHWXCl8NHzr+/GF5qHDrWRo43PFU1XzPe+GGM="
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  pawns:
    image: iproyal/pawns-cli:latest
    container_name: pawns-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    command: -email="nguyentanloc180@gmail.com" -password="Loc123456789" -accept-tos
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  repocket:
    image: repocket/repocket
    container_name: repocket-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - RP_EMAIL=nguyentanloc180@gmail.com
      - RP_API_KEY=8873dd7c-f936-4deb-b128-c15dc54813da
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  packetstream:
    image: packetstream/psclient:latest
    container_name: packetstream-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - CID=wI2
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  earnapp:
    image: madereddy/earnapp
    container_name: earnapp-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - EARNAPP_UUID=${EARNAPP_UUID}
    volumes:
      # This saves your Node ID in a local folder so you don't lose progress
      - ./data/${EARNAPP_UUID}:/etc/earnapp
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
  proxyrack:
    image: proxyrack/pop:latest
    container_name: proxyrack-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - UUID=${PROXYRACK_UUID}
      - API_KEY=TSGIKZS3WX7IZCY0LKX0LHRQEQWUFLGSR5KSHU0J
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  proxybase:
    image: proxybase/proxybase:latest
    container_name: proxybase-${INSTANCE_ID}
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - USER_ID=RW_lbGPdQ9
      - DEVICE_NAME=${PROXYRACK_UUID}
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  #honeygain:
    #image: honeygain/honeygain:latest
    #container_name: honeygain-${INSTANCE_ID}
    #restart: always
    #network_mode: "service:tun2socks"
    #command: -tou-accept -email "@gmail.com" -pass "password" -device ${INSTANCE_ID}
    #cpus: ${APP_CPU_LIMIT:-0.03}
    #mem_limit: ${APP_RAM_LIMIT:-32m}
    #mem_reservation: ${APP_RAM_RESERVE:-16m}

networks:
  my_shared_proxy_network:
    external: true
