services:
  tun2socks:
    container_name: tun2socks-${INSTANCE_ID}
    image: xjasonlyu/tun2socks
    restart: always
    environment:
      - LOGLEVEL=info
      - PROXY=${PROXY_URL}
      - EXTRA_COMMANDS=ip rule add iif lo ipproto udp dport 53 lookup main;
    cap_add:
      - NET_ADMIN
    networks:
      - my_shared_proxy_network
    dns:
      - 1.1.1.1
    devices:
      - /dev/net/tun:/dev/net/tun
    cpus: ${TUN2SOCKS_CPU_LIMIT}
    mem_limit: ${TUN2SOCKS_RAM_LIMIT}

  traffmonetizer:
    image: traffmonetizer/cli_v2
    restart: always
    network_mode: "service:tun2socks"
    command: start accept --token "tbOBkhRHWXCl8NHzr+/GF5qHDrWRo43PFU1XzPe+GGM="

  pawns:
    image: iproyal/pawns-cli:latest
    restart: always
    network_mode: "service:tun2socks"
    command: -email="nguyentanloc180@gmail.com" -password="Loc123456789" -accept-tos
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}

  repocket:
    image: repocket/repocket
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - RP_EMAIL=nguyentanloc180@gmail.com
      - RP_API_KEY=8873dd7c-f936-4deb-b128-c15dc54813da

  packetstream:
    image: packetstream/psclient:latest
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - CID=wI2
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}

  earnapp:
    image: fazalfarhan01/earnapp:lite
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - EARNAPP_UUID=${EARNAPP_UUID}
      - EARNAPP_TERM=yes
    volumes:
      # This saves your Node ID in a local folder so you don't lose progress
      - ./data/earnapp/${INSTANCE_ID}:/etc/earnapp

  proxyrack:
    image: proxyrack/pop:latest
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - UUID=${PROXYRACK_UUID}
      - API_KEY=TSGIKZS3WX7IZCY0LKX0LHRQEQWUFLGSR5KSHU0J
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}

  proxybase:
    image: proxybase/proxybase:latest
    restart: always
    network_mode: "service:tun2socks"
    environment:
      - USER_ID="RW_lbGPdQ9"
      - DEVICE_NAME=${INSTANCE_ID}
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}

  p2pclient:
    image: fazalfarhan01/peer2profit:latest
    restart: always
    network_mode: "service:tun2socks"
    dns: 8.8.8.8
    command: ["nguyentanloc180@gmail.com","-n", ";8.8.8.8"]
    cpus: ${APP_CPU_LIMIT:-0.03}
    mem_limit: ${APP_RAM_LIMIT:-32m}
    mem_reservation: ${APP_RAM_RESERVE:-16m}
  
  #honeygain:
    #image: honeygain/honeygain:latest
    #container_name: honeygain-${INSTANCE_ID}
    #restart: always
    #network_mode: "service:tun2socks"
    #command: -tou-accept -email "nguyentanloc180@gmail.com" -pass "Loc123456789" -device ${INSTANCE_ID}
    #cpus: ${APP_CPU_LIMIT:-0.03}
    #mem_limit: ${APP_RAM_LIMIT:-32m}
    #mem_reservation: ${APP_RAM_RESERVE:-16m}

networks:
  my_shared_proxy_network:
    external: true
